services:
  backend:
    image: ghcr.io/shivambhagat20/cram-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: ghcr.io/shivambhagat20/cram-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
