const mongoose = require('mongoose');
const dotenv = require('dotenv');
const fs = require('fs');
const path = require('path');
const connectDB = require('../config/db');
const Course = require('../models/Course');

// Load environment variables for DB connection string
dotenv.config();

/**
 * Database Seed Function
 * This script reads the parsed courses.json and populates the MongoDB collection.
 * It transforms raw JSON data into the structured format required by the Course Schema.
 */
const seed = async () => {
    try {
        // Established connection to the database
        await connectDB();

        // Read the JSON file generated by the parser script
        const data = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'courses.json'), 'utf-8'));

        console.log(`Seeding ${data.subjects.length} subjects...`);
        let count = 0;

        // Iterate through each subject and its respective courses
        for (const subj of data.subjects) {
            for (const c of subj.courses) {
                // Split courseCode (e.g., "ACC 3110") into Subject and Number for better indexing/searching
                const [s, n] = c.courseCode.split(' ');

                // Using findOneAndUpdate with 'upsert: true' to avoid duplicate entries on re-runs
                await Course.findOneAndUpdate(
                    { course_code: c.courseCode },
                    {
                        title: c.title,
                        subject: s,
                        number: n,
                        course_code: c.courseCode,
                        description: c.description,
                        credits: c.credits,
                        // Transform boolean prerequisite flag into a human-readable string
                        prerequisites: c.hasPrerequisites ? "Yes" : "None",
                        // Flatten attributes array into a single comma-separated string
                        attributes: c.attributes.join(', ')
                    },
                    { upsert: true }
                );
                count++;
            }
        }

        console.log(`Seeded ${count} courses.`);
        process.exit();
    } catch (e) {
        console.error("Seeding Error:", e);
        process.exit(1);
    }
};

// Execute the seed process
seed();
